Plasma Core module development library
FSO-Scripters/fso-scripts pull request #37
Opened 2022-10-04 23:33 UTC by EatThePath

Just a tiny little framework honest.

The Readme has lots of documentation in it. This is a first try of fennel/lua dual submission, so, I'm open to alternate ideas on how to structure it.

2022-10-05 07:56 UTC, BMagnu reviewed
The question here is, what does FSO do, when both the Fnl and the Lua version are present? Do they conflict?

2022-10-06 01:02 UTC, EatThePath commented
If the Fennel package(sold separately) is not installed, .fnl files are invisible to`require` statements and thus only the lua will run. If the package is present then lua files will still be loaded by lua instead of .fnl files, so all should be good. After all, the Lua is equivelent to the code that the runtime would be executing anyay.

...except the modular configs. Drat. I'm calling the fennel compiler to load those, so it's required rather than optional. Hm.

2022-10-06 18:30 UTC, EatThePath commented
I've got an idea on how to handle configs that'll slightly get around this, so drafting for now

2022-11-09 00:58 UTC, EatThePath commented
The config loading is now flexible, and a lua-only solution is provided for people who want to go that route.

2022-11-22 08:39 UTC, BMagnu requested changes
Small comments

2022-11-22 08:39 UTC, BMagnu commented on plasma_core/data/scripts/repl.lua
> +    return engine.restartLog()
Looking at the above Fennel version, this should likely be regenerated to respect the commented out lines regarding the dj-script (which shouldn't be loaded given its not present in these files)

2022-11-22 08:39 UTC, BMagnu commented on plasma_core/data/scripts/plasma_core.fnl
> +    :_ (ba.print (.. "*: " label (if has_label" " "") "type " t ":" (_G.totring output) "\n")))))
THis should be tostring, no?

2022-11-22 08:39 UTC, BMagnu commented on plasma_core/data/scripts/plasma_core.fnl
> +    :_ (ba.print (.. "*: " label (if has_label" " "") "type " t ":" (_G.totring output) "\n")))))
+ regenerating the corresponding lua file, of course

2022-11-26 17:29 UTC, BMagnu approved these changes

2022-11-26 17:49 UTC, merged